// lib/estimatorSeedData.js — Seed data for Estimator_Modules and Estimator_ServiceMatrix

const MODULES = [
  {
    module_id: "PROPERTY_TYPE",
    question: "What type of property is this?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "residential", label: "Residential home", multiplier: 1.0 },
      { value: "commercial",  label: "Commercial building", multiplier: 1.15 },
    ]),
    applies_to: "all",
    notes: "Determines segment routing",
  },
  {
    module_id: "HOME_AGE",
    question: "How old is the home or building?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "pre1960",   label: "Before 1960",   multiplier: 1.35, disqualify: false },
      { value: "1960_1980", label: "1960–1980",      multiplier: 1.2,  disqualify: false },
      { value: "1980_2000", label: "1980–2000",      multiplier: 1.05, disqualify: false },
      { value: "2000plus",  label: "2000 or newer",  multiplier: 1.0,  disqualify: false },
    ]),
    applies_to: "residential",
    notes: "Older wiring increases labor risk",
  },
  {
    module_id: "ATTIC_ACCESS",
    question: "Is there accessible attic space above the work area?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "yes",     label: "Yes – easy access",   multiplier: 1.0 },
      { value: "partial", label: "Limited / low clearance", multiplier: 1.15 },
      { value: "no",      label: "No attic access",     multiplier: 1.3 },
    ]),
    applies_to: "lighting,ceiling",
    notes: "",
  },
  {
    module_id: "CRAWLSPACE_ACCESS",
    question: "Is there crawlspace access below the work area?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "yes", label: "Yes", multiplier: 1.0 },
      { value: "no",  label: "No",  multiplier: 1.15 },
    ]),
    applies_to: "outlets,circuits",
    notes: "",
  },
  {
    module_id: "CEILING_HEIGHT",
    question: "What is the ceiling height in the work area?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "standard", label: "Standard (8–9 ft)",    multiplier: 1.0 },
      { value: "tall",     label: "Tall (10–14 ft)",      multiplier: 1.15 },
      { value: "vaulted",  label: "Vaulted / over 14 ft", multiplier: 1.35 },
    ]),
    applies_to: "lighting,fans",
    notes: "",
  },
  {
    module_id: "WALL_TYPE",
    question: "What is the wall construction type?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "drywall", label: "Drywall",       multiplier: 1.0 },
      { value: "plaster", label: "Plaster",       multiplier: 1.25 },
      { value: "brick",   label: "Brick / masonry", multiplier: 1.45, disqualify: false },
      { value: "other",   label: "Other / unsure", multiplier: 1.2 },
    ]),
    applies_to: "outlets,switches",
    notes: "",
  },
  {
    module_id: "DISTANCE_FROM_PANEL",
    question: "How far is the work area from the electrical panel?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "under10",  label: "Under 10 ft",  multiplier: 1.0 },
      { value: "10to25",   label: "10–25 ft",     multiplier: 1.05 },
      { value: "25to50",   label: "25–50 ft",     multiplier: 1.15 },
      { value: "over50",   label: "Over 50 ft",   multiplier: 1.3 },
    ]),
    applies_to: "outlets,circuits,panel",
    notes: "",
  },
  {
    module_id: "PANEL_SPACE",
    question: "Are there open breaker slots in your electrical panel?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "yes",     label: "Yes – open slots available", multiplier: 1.0 },
      { value: "no",      label: "No – panel is full",        multiplier: 1.4 },
      { value: "unknown", label: "Not sure",                  multiplier: 1.1 },
    ]),
    applies_to: "circuits,panel,ev",
    notes: "Full panel may require subpanel",
  },
  {
    module_id: "PANEL_PHOTO",
    question: "Please upload a clear photo of your electrical panel (inside door open)",
    input_type: "photo",
    options_json: "[]",
    applies_to: "circuits,panel,ev",
    notes: "Required for accurate panel assessment",
  },
  {
    module_id: "EXISTING_BOX",
    question: "Is there an existing electrical box at the fixture location?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "yes", label: "Yes – existing box", multiplier: 1.0 },
      { value: "no",  label: "No – new box needed", multiplier: 1.2 },
    ]),
    applies_to: "lighting,fans",
    notes: "",
  },
  {
    module_id: "FIXTURE_TYPE",
    question: "What type of fixture is being installed?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "recessed",     label: "Recessed / can light",  multiplier: 1.0 },
      { value: "ceiling_fan",  label: "Ceiling fan",           multiplier: 1.1 },
      { value: "chandelier",   label: "Chandelier / pendant",  multiplier: 1.2 },
      { value: "sconce",       label: "Wall sconce",           multiplier: 1.0 },
      { value: "other",        label: "Other",                 multiplier: 1.05 },
    ]),
    applies_to: "lighting",
    notes: "",
  },
  {
    module_id: "QUANTITY",
    question: "How many units / locations?",
    input_type: "number",
    options_json: "[]",
    applies_to: "all",
    notes: "Used for per-unit pricing",
  },
  {
    module_id: "ROOM_TYPE",
    question: "Which room or area is this in?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "bedroom",   label: "Bedroom",        multiplier: 1.0 },
      { value: "living",    label: "Living / family room", multiplier: 1.0 },
      { value: "kitchen",   label: "Kitchen",        multiplier: 1.1 },
      { value: "bathroom",  label: "Bathroom",       multiplier: 1.15 },
      { value: "garage",    label: "Garage",         multiplier: 1.0 },
      { value: "basement",  label: "Basement",       multiplier: 1.05 },
      { value: "outdoor",   label: "Outdoor / exterior", multiplier: 1.2 },
    ]),
    applies_to: "outlets,switches,lighting",
    notes: "",
  },
  {
    module_id: "OUTDOOR_INSTALL",
    question: "Is this an outdoor or exterior installation?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "yes_covered",  label: "Yes – covered / sheltered", multiplier: 1.1 },
      { value: "yes_exposed",  label: "Yes – exposed to weather",  multiplier: 1.25 },
      { value: "no",           label: "No – indoor",               multiplier: 1.0 },
    ]),
    applies_to: "outdoor,landscape",
    notes: "",
  },
  {
    module_id: "NEW_DEDICATED_CIRCUIT",
    question: "Does this require running a new dedicated circuit?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "yes",   label: "Yes",         multiplier: 1.35 },
      { value: "no",    label: "No",          multiplier: 1.0 },
      { value: "unsure", label: "Not sure",   multiplier: 1.1 },
    ]),
    applies_to: "ev,hot_tub,appliance",
    notes: "",
  },
  {
    module_id: "WORK_AREA_PHOTOS",
    question: "Upload 1–3 photos of the work area (helps us confirm the estimate)",
    input_type: "photo",
    options_json: "[]",
    applies_to: "all",
    notes: "Recommended for all jobs",
  },
  {
    module_id: "UNCERTAINTY_BUFFER",
    question: "Overall, how straightforward does this job seem?",
    input_type: "single_select",
    options_json: JSON.stringify([
      { value: "simple",  label: "Very straightforward",         multiplier: 1.0 },
      { value: "moderate", label: "Some complexity expected",    multiplier: 1.1 },
      { value: "complex", label: "Multiple unknowns / older home", multiplier: 1.2 },
    ]),
    applies_to: "all",
    notes: "Customer self-assessment buffer",
  },
];

const SERVICES = [
  // ── SITE VISIT REQUIRED ─────────────────────────────────────────────────────
  { service_id: "TROUBLESHOOT_FLICKER",    service_name: "Troubleshooting – Flickering Lights",      segment: "residential", tier: "site_visit_required",    modules_csv: "PROPERTY_TYPE,HOME_AGE,WORK_AREA_PHOTOS",                                                              base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "REWIRE_WHOLE_HOUSE",      service_name: "Whole-House Rewiring",                     segment: "residential", tier: "site_visit_required",    modules_csv: "PROPERTY_TYPE,HOME_AGE,PANEL_PHOTO,WORK_AREA_PHOTOS",                                                  base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "REWIRE_PARTIAL",          service_name: "Partial Home Rewiring",                    segment: "residential", tier: "site_visit_required",    modules_csv: "PROPERTY_TYPE,HOME_AGE,ATTIC_ACCESS,PANEL_PHOTO,WORK_AREA_PHOTOS",                                     base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "REWIRE_COMMERCIAL",       service_name: "Commercial Rewiring",                      segment: "commercial",  tier: "site_visit_required",    modules_csv: "PROPERTY_TYPE,CEILING_HEIGHT,PANEL_PHOTO,WORK_AREA_PHOTOS",                                            base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "FIRE_ALARM",              service_name: "Fire Alarm System",                        segment: "commercial",  tier: "site_visit_required",    modules_csv: "PROPERTY_TYPE,CEILING_HEIGHT,WORK_AREA_PHOTOS",                                                        base_price_mode: "placeholder",         enabled: "TRUE" },
  { service_id: "TRANSFORMER_INSTALL",     service_name: "Transformer Installation",                 segment: "commercial",  tier: "site_visit_required",    modules_csv: "PROPERTY_TYPE,WORK_AREA_PHOTOS",                                                                       base_price_mode: "placeholder",         enabled: "TRUE" },
  { service_id: "GENERATOR_STANDBY",       service_name: "Standby Generator Installation",           segment: "residential", tier: "site_visit_required",    modules_csv: "PROPERTY_TYPE,HOME_AGE,PANEL_SPACE,PANEL_PHOTO,WORK_AREA_PHOTOS",                                     base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "GENERATOR_BACKUP",        service_name: "Backup Generator Installation & Maintenance", segment: "residential", tier: "site_visit_required", modules_csv: "PROPERTY_TYPE,HOME_AGE,PANEL_SPACE,PANEL_PHOTO,WORK_AREA_PHOTOS",                                     base_price_mode: "existing_calculator", enabled: "TRUE" },
  // ── INSTANT WITH SAFEGUARDS ─────────────────────────────────────────────────
  { service_id: "CEILING_FAN_INSTALL",     service_name: "Ceiling Fan Installation",                 segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,CEILING_HEIGHT,ATTIC_ACCESS,EXISTING_BOX,FIXTURE_TYPE,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",  base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "LIGHT_FIXTURE_INSTALL",   service_name: "Light Fixture Installation",               segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,CEILING_HEIGHT,ATTIC_ACCESS,EXISTING_BOX,FIXTURE_TYPE,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",  base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "RECESSED_LIGHTING",       service_name: "Recessed Lighting Installation",           segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,CEILING_HEIGHT,ATTIC_ACCESS,EXISTING_BOX,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",               base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "DIMMER_SWITCH",           service_name: "Dimmer / Smart Switch Installation",       segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,WALL_TYPE,DISTANCE_FROM_PANEL,ROOM_TYPE,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",               base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "OUTLET_INSTALL",          service_name: "Outlet / Receptacle Installation",         segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,WALL_TYPE,DISTANCE_FROM_PANEL,ROOM_TYPE,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",               base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "GFCI_OUTLET",             service_name: "GFCI Outlet Installation",                 segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,WALL_TYPE,DISTANCE_FROM_PANEL,ROOM_TYPE,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",               base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "EV_CHARGER",              service_name: "EV Charger Installation",                  segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,PANEL_SPACE,PANEL_PHOTO,DISTANCE_FROM_PANEL,NEW_DEDICATED_CIRCUIT,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER", base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "HOT_TUB_CIRCUIT",         service_name: "Hot Tub / Spa Electrical Circuit",         segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,PANEL_SPACE,PANEL_PHOTO,DISTANCE_FROM_PANEL,NEW_DEDICATED_CIRCUIT,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER", base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "PANEL_UPGRADE",           service_name: "Electrical Panel Upgrade",                 segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,PANEL_PHOTO,PANEL_SPACE,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",                                         base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "SUBPANEL_INSTALL",        service_name: "Sub-Panel Installation",                   segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,PANEL_PHOTO,PANEL_SPACE,DISTANCE_FROM_PANEL,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",                     base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "SURGE_PROTECTOR",         service_name: "Whole-Home Surge Protector",               segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,PANEL_PHOTO,PANEL_SPACE,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",                                         base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "OUTDOOR_LIGHTING",        service_name: "Outdoor / Landscape Lighting",             segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,OUTDOOR_INSTALL,WALL_TYPE,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",                              base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "MOTION_SECURITY_LIGHT",   service_name: "Motion / Security Light Installation",     segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,OUTDOOR_INSTALL,WALL_TYPE,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",                              base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "SMOKE_CO_DETECTOR",       service_name: "Smoke / CO Detector Installation",         segment: "residential", tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,HOME_AGE,CEILING_HEIGHT,ATTIC_ACCESS,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",                            base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "COMM_LIGHTING_RETROFIT",  service_name: "Commercial Lighting Retrofit",             segment: "commercial",  tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,CEILING_HEIGHT,FIXTURE_TYPE,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",                                     base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "BALLAST_REPLACE",         service_name: "Ballast / Bulb Replacement",               segment: "commercial",  tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,CEILING_HEIGHT,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",                                                  base_price_mode: "existing_calculator", enabled: "TRUE" },
  { service_id: "EXIT_EMERGENCY_LIGHTS",   service_name: "Exit / Emergency Light Installation",      segment: "commercial",  tier: "instant_with_safeguards", modules_csv: "PROPERTY_TYPE,CEILING_HEIGHT,QUANTITY,WORK_AREA_PHOTOS,UNCERTAINTY_BUFFER",                                                  base_price_mode: "existing_calculator", enabled: "TRUE" },
];

module.exports = { MODULES, SERVICES };
